server:
  port: 8765

spring:
  application:
    name: gateway-server

  
  cloud:
    gateway:
      routes:
        - id: notification-ms
          uri: lb://notification-ms
          predicates:
            - Path=/notification/**
            
        - id: notification-websocket-ms
          uri: lb:ws://notification-ms
          predicates:          
            - Path=/ws/notification/**
            
        - id: publisher-ms
          uri: lb://publisher-ms
          predicates:
            - Path=/publisher/**
        
        - id: chat-ms
          uri: lb://chat-ms
          predicates:
            - Path=/chat/**
        
        - id: chat-websocket-ms
          uri: lb:ws://chat-ms
          predicates:          
            - Path=/ws/chat/**
            
        - id: post-ms
          uri: lb://post-ms
          predicates:
            - Path=/post/**
        
        - id: media-ms
          uri: lb://media-ms
          predicates:
            - Path=/video/**,/image/**
            
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    hostname: ${EUREKA_SERVER_HOST:localhost}
    ip-address: ${EUREKA_CLIENT_IP_ADDRESS:localhost}

sphere:
  utils:
    cors:
      allowOrigins:
        - "http://localhost:3000"
        - "http://localhost"
        - "http://192.168.1.6:3000"
        - "http://192.168.1.6"
