server:
  port: 8002

spring:
  application:
    name: publisher-ms
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${OAUTH2_ISSUER_HOST:localhost}:${OAUTH2_ISSUER_PORT:9001}
      
  rabbitmq:
    username: guest
    password: guest
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    queues: 
      friend-request: friend-request
      create-post-request: create-post-request
  
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    hostname: ${EUREKA_SERVER_HOST:localhost}
    ip-address: ${EUREKA_CLIENT_IP_ADDRESS:localhost}
    