server:
  port: 8003

spring:
  application:
    name: chat-ms
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${OAUTH2_ISSUER_HOST:localhost}:${OAUTH2_ISSUER_PORT:9001}
      
  rabbitmq:
    username: guest
    password: guest
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    queues: 
      create-chat-request: create-chat-request
  
  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3308}/${DB_NAME:chat_db}?useTimezone=true&serverTimezone=UTC
        username: ${DB_USER:root}
        password: ${DB_PASSWORD:root}
  jpa:
      hibernate:
          ddl-auto: create
      show-sql: false
      open-in-view: true
      
  
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: ${EUREKA_SERVER_HOST:localhost}
    preferIpAddress: true
    ip-address: ${EUREKA_CLIENT_IP_ADDRESS:localhost}

sphere:
  websockets:
    path: /ws/chat/v1
    allowOrigins:
      - "http://localhost:3000"
      - "http://localhost"
      - "http://192.168.1.6:3000"
      - "http://192.168.1.6"
    